import { FaLock } from "react-icons/fa";
import { FaUnlock } from "react-icons/fa";
import { BsInfoCircle } from "react-icons/bs";
import { FaUserShield } from "react-icons/fa";
import { TiEdit } from "react-icons/ti";
import { FaTrash } from "react-icons/fa";
import { FaSignInAlt } from "react-icons/fa";
import { FaSyncAlt } from "react-icons/fa";
import { FaSignOutAlt } from "react-icons/fa";
import { FaUser } from "react-icons/fa";
import { FaKey } from "react-icons/fa";

export const BlockIcon = () => <FaLock />;
export const DeployIcon = () => <FaUnlock />;
export const MoreIcon = () => <BsInfoCircle />;
export const AdminIcon = () => <FaUserShield />;
export const CreateIcon = () => <TiEdit />;
export const DeleteIcon = () => <FaTrash />;
export const LogInIcon = () => <FaSignInAlt />;
export const LogOutIcon = () => <FaSignOutAlt />;
export const UpdateIcon = () => <FaSyncAlt />;
export const UserIcon = () => <FaUser />;
export const PasswordIcon = () => <FaKey />;
